name: Angular+Docker+Git

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Install & Tests
        run: |
          npm install
          npm test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build
        run: docker build -t actions .
      - name: Tags
        run: |
          docker tag actions ${{ secrets.DOCKER_HUB_USER }}/back:${{ github.sha }}
          docker tag actions ${{ secrets.DOCKER_HUB_USER }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/actions:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/actions:latest
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with: 
          app-name: actions
          publish-profile: ${{ secrets.AZURE_TOKEN }}
  