name: Angular+git+
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: gitactions   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'     
jobs:
  build-and-deploy:
    name: Mi primer job
    runs-on: ubuntu-latest
    container: 
      image: ubuntu
    steps:
      - name: Ejecutar deploy
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: npm i
             npm test
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: alejandralopezimexhs/ubuntu
          tag_with_ref: true
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  