name: Mi primer workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar deploy
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: |
          npm i
          npm run-script build
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  