name: workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Mi primer job
    runs-on: ubuntu-latest
    container: 
      image: ubuntu
    steps:
      - name: Ejecutar deploy
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: npm i
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with: 
          app-name: actions
          publish-profile: ${{ secrets.AZURE_TOKEN }}
  