name: Mi primer workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Mi primer job
    runs-on: ubuntu-latest
    container: 
      image: ubuntu
    steps:
      - name: Ejecutar deploy
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: npm i
      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t actions .
      - name: Tags
        run: |
          docker tag actions ${{ secrets.DOCKER_HUB_USERNAME }}/actions:${{ github.sha }}
          docker tag actions ${{ secrets.DOCKER_HUB_USERNAME }}/actions:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/actions:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/actions:latest
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with: 
          app-name: actions
          publish-profile: ${{ secrets.AZURE_TOKEN }}
  