name: workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Mi primer job
    runs-on: ubuntu-latest
    container: 
      image: ubuntu
    steps:
      - name: Ejecutar deploy
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: npm i
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: alejandralopezimexhs/ubuntu
          tag_with_ref: true
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with: 
          app-name: actions
          publish-profile: ${{ secrets.AZURE_TOKEN }}
  